// ACTION TYPES THAT ARE GOING TO BE USE IN THE APP
export const LOAD_FILM = "LOAD_FILM";
export const LOAD_PLANET = "LOAD_PLANET";
export const LOAD_PERSON = "LOAD_PERSON";
export const RESET_ALL = "RESET_ALL";
